"""resume_ownership_refactor

Revision ID: 0ea7778d0628
Revises: 6424176f6734
Create Date: 2026-04-24 22:17:18.904668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ea7778d0628'
down_revision: Union[str, None] = '6424176f6734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('cv_text', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.Text(), nullable=False),
    sa.Column('analyzed_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_analyzed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'file_hash')
    )
    op.create_index(op.f('ix_resumes_file_hash'), 'resumes', ['file_hash'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('match_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('jd_hash', sa.Text(), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('match_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'jd_hash')
    )
    op.create_index(op.f('ix_match_cache_resume_id'), 'match_cache', ['resume_id'], unique=False)
    op.create_table('token_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('was_cached', sa.Boolean(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_user_id'), 'token_usage', ['user_id'], unique=False)
    op.add_column('candidate_profiles', sa.Column('migrated', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # Step 1: Add resume_id as nullable=True to avoid breaking existing rows
    op.add_column('sessions', sa.Column('resume_id', sa.UUID(), nullable=True))
    op.add_column('sessions', sa.Column('job_description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_sessions_resume_id'), 'sessions', ['resume_id'], unique=False)
    op.create_foreign_key('fk_sessions_resume_id_resumes', 'sessions', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')

    # Step 2: Data Migration
    import uuid
    import hashlib
    from sqlalchemy.sql import text
    conn = op.get_bind()
    
    # Fetch all existing sessions with their linked profile
    sessions = conn.execute(text(
        "SELECT s.id, s.user_id, s.profile_id, p.cv_text, p.job_description, p.skills_extracted, p.match_report "
        "FROM sessions s "
        "JOIN candidate_profiles p ON s.profile_id = p.id "
        "WHERE p.migrated = false"
    )).fetchall()
    
    migrated_count = 0
    for session in sessions:
        session_id, user_id, profile_id, cv_text, jd, skills, match = session
        
        # We need a file hash. Since we don't have the original file, we hash the cv_text
        cv_text = cv_text or ""
        file_hash = hashlib.sha256(cv_text.encode('utf-8')).hexdigest()
        
        # Check if we already created a resume for this user+hash
        existing_resume = conn.execute(text(
            "SELECT id FROM resumes WHERE user_id = :user_id AND file_hash = :hash"
        ), {"user_id": user_id, "hash": file_hash}).fetchone()
        
        if existing_resume:
            resume_id = existing_resume[0]
        else:
            resume_id = uuid.uuid4()
            analyzed_profile = None
            if skills:
                # Approximate reconstructed JobProfile
                analyzed_profile = {
                    "inferred_role": "Migrated Role",
                    "inferred_experience_level": "mid",
                    "core_skills": skills.get("skills", []),
                    "technical_stack": [],
                    "key_achievements": []
                }
            import json
            conn.execute(text(
                "INSERT INTO resumes (id, user_id, filename, cv_text, file_hash, analyzed_profile, is_analyzed, created_at, updated_at) "
                "VALUES (:id, :user, :filename, :text, :hash, :profile, true, now(), now())"
            ), {
                "id": resume_id, "user": user_id, "filename": "migrated_cv.txt",
                "text": cv_text, "hash": file_hash, 
                "profile": json.dumps(analyzed_profile) if analyzed_profile else None
            })
            
            # If there was a match report, create a match cache entry
            if match and jd:
                jd_hash = hashlib.sha256(jd.encode('utf-8')).hexdigest()
                conn.execute(text(
                    "INSERT INTO match_cache (id, resume_id, jd_hash, jd_text, match_report, created_at) "
                    "VALUES (:id, :resume, :hash, :text, :report, now()) "
                    "ON CONFLICT DO NOTHING"
                ), {
                    "id": uuid.uuid4(), "resume": resume_id, "hash": jd_hash,
                    "text": jd[:500], "report": json.dumps(match)
                })
        
        # Update session with resume_id and job_description
        conn.execute(text(
            "UPDATE sessions SET resume_id = :resume_id, job_description = :jd WHERE id = :session_id"
        ), {"resume_id": resume_id, "jd": jd, "session_id": session_id})
        
        # Mark profile as migrated
        conn.execute(text(
            "UPDATE candidate_profiles SET migrated = true WHERE id = :profile_id"
        ), {"profile_id": profile_id})
        
        migrated_count += 1

    print(f"Migrated {migrated_count} sessions to new resume architecture.")

    # Step 3: Delete any remaining sessions without a resume (or handle them)
    conn.execute(text("DELETE FROM sessions WHERE resume_id IS NULL"))

    # Step 4: Alter resume_id to be NOT NULL
    op.alter_column('sessions', 'resume_id', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_resume_id'), table_name='sessions')
    op.drop_column('sessions', 'job_description')
    op.drop_column('sessions', 'resume_id')
    op.drop_column('candidate_profiles', 'migrated')
    op.drop_index(op.f('ix_token_usage_user_id'), table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index(op.f('ix_match_cache_resume_id'), table_name='match_cache')
    op.drop_table('match_cache')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_file_hash'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
