"""add_react_scratchpad_to_exchange

Revision ID: 6424176f6734
Revises: 829ed56ef538
Create Date: 2026-04-22 22:50:07.974864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6424176f6734'
down_revision: Union[str, None] = '829ed56ef538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('react_scratchpad', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchanges', 'react_scratchpad')
    # ### end Alembic commands ###
